version: '2.2'

services:
#   cubestore:
#     image: cubejs/cubestore:latest
#     ports:
#       - 3030:3030
#     environment:
#       - CUBESTORE_REMOTE_DIR=/cube/data
#     volumes:
#       - .cubestore:/cube/data
  cube:
    image: cubejs/cube:latest
    ports:
      # 4000 is the port for the Cube.js API
      - ${PORT}:4000
      # 3000 is the port for the Dashboard app, and is available only in
      # development mode
    #   - ${APP_DASHBOARD_PORT}:3000
    env_file:
      - .env
    # depends_on:
    #   - cubestore
    # links:
    #   - cubestore
    volumes:
      - .:/cube/conf
    restart: "on-failure"
